# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15sSy4LDPgsFnN6gtn-9tS18lHusxPqg8
"""

import streamlit as st
import random
import numpy as np
import pandas as pd
import threading
import time

from utils.data import DATASETS, DEFAULT_PARAMS
from utils.genetic import algoritma_genetika, hitung_kontribusi, hitung_objektif, hitung_fitness
from utils.charts import (
    plot_konvergensi, plot_layout_grid,
    plot_kontribusi_bar, plot_flow_heatmap
)

# ── Page config ──────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="Optimasi Tata Letak RS — Algoritma Genetika",
    page_icon="🏥",
    layout="wide",
    initial_sidebar_state="expanded"
)

# ── Custom CSS ───────────────────────────────────────────────────────────────
st.markdown("""
<style>
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@400;600&display=swap');

html, body, [class*="css"] {
    font-family: 'Inter', sans-serif;
}

.stApp {
    background: #F8FAFC;
}

/* Header utama */
.hero-header {
    background: linear-gradient(135deg, #0F172A 0%, #1E3A5F 60%, #0EA5E9 100%);
    border-radius: 16px;
    padding: 2rem 2.5rem;
    margin-bottom: 1.5rem;
    color: white;
}
.hero-header h1 {
    font-size: 1.75rem;
    font-weight: 700;
    margin: 0 0 0.3rem 0;
    letter-spacing: -0.02em;
}
.hero-header p {
    font-size: 0.9rem;
    opacity: 0.75;
    margin: 0;
}

/* Metric cards */
.metric-card {
    background: white;
    border: 1px solid #E2E8F0;
    border-radius: 12px;
    padding: 1.25rem 1.5rem;
    text-align: center;
    box-shadow: 0 1px 4px rgba(0,0,0,0.05);
}
.metric-card .value {
    font-size: 1.6rem;
    font-weight: 700;
    font-family: 'JetBrains Mono', monospace;
    color: #0EA5E9;
    letter-spacing: -0.02em;
}
.metric-card .label {
    font-size: 0.75rem;
    color: #64748B;
    text-transform: uppercase;
    letter-spacing: 0.06em;
    margin-top: 0.3rem;
}

/* Section title */
.section-title {
    font-size: 1rem;
    font-weight: 600;
    color: #0F172A;
    padding-bottom: 0.5rem;
    border-bottom: 2px solid #E2E8F0;
    margin-bottom: 1rem;
}

/* Tag badge */
.badge {
    display: inline-block;
    background: #EFF6FF;
    color: #1D4ED8;
    border-radius: 6px;
    padding: 2px 10px;
    font-size: 0.75rem;
    font-weight: 600;
    margin-right: 4px;
}

/* Result table */
.result-table {
    font-family: 'JetBrains Mono', monospace;
    font-size: 0.82rem;
}

/* Sidebar label */
.sidebar-label {
    font-size: 0.78rem;
    font-weight: 600;
    color: #475569;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    margin-bottom: 0.25rem;
}

/* Alert box */
.info-box {
    background: #EFF6FF;
    border-left: 4px solid #0EA5E9;
    border-radius: 0 8px 8px 0;
    padding: 0.75rem 1rem;
    font-size: 0.85rem;
    color: #1E40AF;
    margin: 0.75rem 0;
}

/* Progress text */
.progress-label {
    font-family: 'JetBrains Mono', monospace;
    font-size: 0.82rem;
    color: #475569;
}
</style>
""", unsafe_allow_html=True)


# ── Sidebar ───────────────────────────────────────────────────────────────────
with st.sidebar:
    st.markdown("### 🏥 Konfigurasi")
    st.markdown("---")

    dataset_choice = st.selectbox(
        "Pilih Dataset",
        list(DATASETS.keys()),
        help="Pilih ukuran dataset yang ingin dioptimasi."
    )

    st.markdown("---")
    st.markdown("**Parameter Algoritma Genetika**")

    defaults = DEFAULT_PARAMS[dataset_choice]

    popsize = st.slider("Ukuran Populasi", 10, 300,
                        defaults["popsize"], step=10)
    max_gen = st.slider("Maks. Generasi", 50, 1000,
                        defaults["max_gen"], step=50)
    elite_count = st.slider("Jumlah Elite", 1, 10,
                             defaults["elite_count"])
    pc = st.slider("Prob. Crossover (pc)", 0.5, 1.0,
                   defaults["pc"], step=0.05)
    pm = st.slider("Prob. Mutasi (pm)", 0.01, 0.5,
                   defaults["pm"], step=0.01)

    seed_val = st.number_input("Random Seed", min_value=0,
                                max_value=9999, value=42, step=1)

    st.markdown("---")
    run_btn  = st.button("▶ Jalankan Optimasi", type="primary",
                         use_container_width=True)
    stop_btn = st.button("⏹ Hentikan", use_container_width=True)

    st.markdown("---")
    st.markdown("""
    <div style="font-size:0.75rem; color:#94A3B8; line-height:1.6;">
    <b>Kelompok 8</b><br>
    Matematika — Universitas Airlangga<br>
    <em>Quadratic Assignment Problem</em><br>
    Algoritma Genetika
    </div>
    """, unsafe_allow_html=True)


# ── Header ───────────────────────────────────────────────────────────────────
st.markdown("""
<div class="hero-header">
    <h1>🏥 Optimasi Tata Letak Departemen Rumah Sakit</h1>
    <p>Algoritma Genetika &nbsp;·&nbsp; Quadratic Assignment Problem &nbsp;·&nbsp; Kelompok 8 · Matematika UNAIR 2026</p>
</div>
""", unsafe_allow_html=True)

# ── State management ─────────────────────────────────────────────────────────
if "result" not in st.session_state:
    st.session_state.result = None
if "running" not in st.session_state:
    st.session_state.running = False
if "stop_event" not in st.session_state:
    st.session_state.stop_event = threading.Event()


# ── Stop handler ─────────────────────────────────────────────────────────────
if stop_btn and st.session_state.running:
    st.session_state.stop_event.set()
    st.session_state.running = False


# ── Run optimasi ─────────────────────────────────────────────────────────────
if run_btn:
    flow, dist, dept_names = DATASETS[dataset_choice]
    n = len(dept_names)

    st.session_state.running = True
    st.session_state.stop_event = threading.Event()
    st.session_state.result = None

    random.seed(seed_val)
    np.random.seed(seed_val)

    # UI progress
    st.markdown(f'<div class="info-box">⚙️ Menjalankan optimasi untuk <b>{dataset_choice}</b> …</div>',
                unsafe_allow_html=True)

    progress_bar  = st.progress(0)
    status_text   = st.empty()
    live_col1, live_col2 = st.columns(2)
    live_best_ph  = live_col1.empty()
    live_avg_ph   = live_col2.empty()

    riwayat_best_live = []
    riwayat_avg_live  = []
    chart_ph = st.empty()

    def cb(gen, max_g, best_z, avg_z):
        riwayat_best_live.append(best_z)
        riwayat_avg_live.append(avg_z)
        pct = gen / max_g
        progress_bar.progress(pct)
        status_text.markdown(
            f'<p class="progress-label">Generasi <b>{gen}</b> / {max_g} &nbsp;|&nbsp; '
            f'Best Z = <b>{best_z:,.0f}</b> &nbsp;|&nbsp; Avg Z = {avg_z:,.0f}</p>',
            unsafe_allow_html=True
        )
        live_best_ph.metric("Best Z (sekarang)", f"{best_z:,.0f}")
        live_avg_ph.metric("Avg Z (sekarang)", f"{avg_z:,.0f}")
        # Update chart tiap 25 generasi agar tidak lambat
        if gen % 25 == 0 or gen == max_g:
            fig = plot_konvergensi(riwayat_best_live, riwayat_avg_live, dataset_choice)
            chart_ph.plotly_chart(fig, use_container_width=True, key=f"live_{gen}")

    t_start = time.time()
    best_k, best_z, best_f, riwayat_best, riwayat_avg, elapsed = algoritma_genetika(
        flow, dist, dept_names,
        popsize=popsize, elite_count=elite_count,
        pc=pc, pm=pm, max_gen=max_gen,
        progress_callback=cb,
        stop_event=st.session_state.stop_event
    )

    kontribusi = hitung_kontribusi(best_k, flow, dist)

    st.session_state.result = {
        "dataset":       dataset_choice,
        "flow":          flow,
        "dist":          dist,
        "dept_names":    dept_names,
        "best_k":        best_k,
        "best_z":        best_z,
        "best_f":        best_f,
        "riwayat_best":  riwayat_best,
        "riwayat_avg":   riwayat_avg,
        "elapsed":       elapsed,
        "kontribusi":    kontribusi,
        "params":        dict(popsize=popsize, elite_count=elite_count,
                              pc=pc, pm=pm, max_gen=max_gen, seed=seed_val),
    }
    st.session_state.running = False
    progress_bar.progress(1.0)
    status_text.markdown(
        f'<p class="progress-label">✅ Selesai dalam <b>{elapsed:.2f} detik</b></p>',
        unsafe_allow_html=True
    )
    st.rerun()


# ── Tampilkan hasil ───────────────────────────────────────────────────────────
if st.session_state.result:
    r = st.session_state.result

    # Metric summary
    st.markdown('<div class="section-title">📊 Ringkasan Hasil</div>',
                unsafe_allow_html=True)
    mc1, mc2, mc3, mc4 = st.columns(4)
    with mc1:
        st.markdown(f"""
        <div class="metric-card">
            <div class="value">{r['best_z']:,.0f}</div>
            <div class="label">Nilai Objektif (Z)</div>
        </div>""", unsafe_allow_html=True)
    with mc2:
        st.markdown(f"""
        <div class="metric-card">
            <div class="value">{r['best_f']:.4e}</div>
            <div class="label">Fitness Terbaik</div>
        </div>""", unsafe_allow_html=True)
    with mc3:
        st.markdown(f"""
        <div class="metric-card">
            <div class="value">{r['elapsed']:.2f}s</div>
            <div class="label">Waktu Komputasi</div>
        </div>""", unsafe_allow_html=True)
    with mc4:
        st.markdown(f"""
        <div class="metric-card">
            <div class="value">{len(r['riwayat_best'])}</div>
            <div class="label">Total Generasi</div>
        </div>""", unsafe_allow_html=True)

    st.markdown("<br>", unsafe_allow_html=True)

    # ── Tabs ─────────────────────────────────────────────────────
    tab1, tab2, tab3, tab4 = st.tabs([
        "📈 Konvergensi",
        "🗺 Tata Letak Optimal",
        "📋 Tabel Penugasan",
        "🔬 Analisis Lanjut"
    ])

    with tab1:
        st.plotly_chart(
            plot_konvergensi(r["riwayat_best"], r["riwayat_avg"], r["dataset"]),
            use_container_width=True
        )
        imp = sum(1 for i in range(1, len(r["riwayat_best"]))
                  if r["riwayat_best"][i] < r["riwayat_best"][i-1])
        st.markdown(f"""
        <div class="info-box">
        Terjadi <b>{imp} perbaikan solusi</b> sepanjang {len(r['riwayat_best'])} generasi.
        Penurunan Z dari generasi 1 ke akhir:
        <b>{r['riwayat_best'][0]:,.0f} → {r['riwayat_best'][-1]:,.0f}</b>
        ({(1 - r['riwayat_best'][-1]/r['riwayat_best'][0])*100:.1f}% perbaikan).
        </div>
        """, unsafe_allow_html=True)

    with tab2:
        st.plotly_chart(
            plot_layout_grid(r["best_k"], r["dept_names"]),
            use_container_width=True
        )

    with tab3:
        dept_names = r["dept_names"]
        rows = []
        for loc_i, dept_n in enumerate(r["best_k"]):
            nama = dept_names[dept_n]
            kode = nama.split('(')[-1].replace(')', '')
            rows.append({
                "Lokasi": loc_i + 1,
                "Kode": kode,
                "Nama Departemen": nama.split('(')[0].strip(),
                "Kontribusi Biaya": int(r["kontribusi"][dept_n - 1])
            })

        df = pd.DataFrame(rows)
        df_show = df.copy()
        df_show["Kontribusi Biaya"] = df_show["Kontribusi Biaya"].map("{:,.0f}".format)

        st.dataframe(df_show, use_container_width=True, hide_index=True)

        # Download
        csv = df.to_csv(index=False).encode("utf-8")
        st.download_button(
            "⬇ Download CSV",
            data=csv,
            file_name=f"hasil_{r['dataset'].replace(' ', '_').replace('(', '').replace(')', '')}.csv",
            mime="text/csv"
        )

    with tab4:
        col_a, col_b = st.columns([1, 1])
        with col_a:
            st.plotly_chart(
                plot_kontribusi_bar(r["best_k"], r["dept_names"], r["kontribusi"]),
                use_container_width=True
            )
        with col_b:
            st.plotly_chart(
                plot_flow_heatmap(r["flow"], r["dept_names"]),
                use_container_width=True
            )

        # Parameter summary
        st.markdown("**Parameter yang Digunakan**")
        p = r["params"]
        st.json({
            "Dataset": r["dataset"],
            "Ukuran Populasi": p["popsize"],
            "Maks. Generasi": p["max_gen"],
            "Elite Count": p["elite_count"],
            "Prob. Crossover (pc)": p["pc"],
            "Prob. Mutasi (pm)": p["pm"],
            "Random Seed": p["seed"],
        })

else:
    # Placeholder saat belum ada hasil
    st.markdown("""
    <div style="
        background: white;
        border: 2px dashed #CBD5E1;
        border-radius: 16px;
        padding: 3rem;
        text-align: center;
        color: #94A3B8;
    ">
        <div style="font-size: 3rem; margin-bottom: 1rem;">🧬</div>
        <div style="font-size: 1.1rem; font-weight: 600; color: #64748B;">
            Belum ada hasil optimasi
        </div>
        <div style="font-size: 0.85rem; margin-top: 0.5rem;">
            Pilih dataset dan parameter di sidebar, lalu klik <b>▶ Jalankan Optimasi</b>.
        </div>
    </div>
    """, unsafe_allow_html=True)

    # Tampilkan info dataset
    st.markdown("<br>", unsafe_allow_html=True)
    st.markdown('<div class="section-title">ℹ️ Informasi Dataset</div>',
                unsafe_allow_html=True)

    flow, dist, dept_names = DATASETS[list(DATASETS.keys())[0]]

    info_data = {
        "Dataset": ["Data Kecil (n=5)", "Data Sedang (n=12)", "Data Besar (n=19)"],
        "Jumlah Dept.": [5, 12, 19],
        "Popsize Default": [30, 80, 150],
        "MaxGen Default": [200, 500, 800],
    }
    st.dataframe(pd.DataFrame(info_data), use_container_width=True, hide_index=True)