# -*- coding: utf-8 -*-
"""genetic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qxAAFAGN8RCotUiHgZDR36EBm_gVhnrq
"""

import numpy as np
import random
import copy
import time


def hitung_objektif(kromosom, flow, dist):
    """Hitung nilai fungsi objektif Z = Σ F[a][b] * D[π(a)][π(b)]"""
    n = len(kromosom)
    z = 0.0
    perm = [k - 1 for k in kromosom]
    for a in range(n):
        for b in range(n):
            z += flow[a][b] * dist[perm[a]][perm[b]]
    return z


def hitung_fitness(z):
    return 1.0 / (z + 1)


def bangkitkan_populasi(popsize, n):
    """Bangkitkan populasi awal via bilangan random → ranking → permutasi."""
    populasi = []
    for _ in range(popsize):
        rand_vals = [random.random() for _ in range(n)]
        sorted_idx = sorted(range(n), key=lambda x: rand_vals[x])
        kromosom = [0] * n
        for rank, orig_idx in enumerate(sorted_idx):
            kromosom[orig_idx] = rank + 1
        populasi.append(kromosom)
    return populasi


def order_crossover(p1, p2):
    """Order Crossover (OX) - Davis (1985)."""
    n = len(p1)
    c1, c2 = sorted(random.sample(range(n), 2))

    child = [None] * n
    for i in range(c1, c2 + 1):
        child[i] = p1[i]

    used = set(child[c1:c2 + 1])
    remaining = []
    for i in range(n):
        g = p2[(c2 + 1 + i) % n]
        if g not in used:
            remaining.append(g)

    idx = 0
    for i in range(n):
        if child[i] is None:
            child[i] = remaining[idx]
            idx += 1
    return child


def reciprocal_exchange_mutation(kromosom):
    """Reciprocal Exchange Mutation – tukar 2 posisi acak."""
    child = kromosom[:]
    n = len(child)
    r1 = random.randint(0, n - 1)
    r2 = random.randint(0, n - 1)
    while r2 == r1:
        r2 = random.randint(0, n - 1)
    child[r1], child[r2] = child[r2], child[r1]
    return child


def algoritma_genetika(flow, dist, dept_names,
                       popsize=50, elite_count=2,
                       pc=0.8, pm=0.2, max_gen=500,
                       progress_callback=None,
                       stop_event=None):
    """
    Algoritma Genetika untuk QAP.
    progress_callback(gen, max_gen, best_z, avg_z) dipanggil tiap generasi.
    stop_event: threading.Event – set untuk menghentikan lebih awal.
    """
    n = len(dept_names)
    riwayat_best = []
    riwayat_avg  = []

    populasi = bangkitkan_populasi(popsize, n)

    best_kromosom = None
    best_z = float('inf')
    best_fitness = 0.0

    start_time = time.time()

    for gen in range(1, max_gen + 1):
        if stop_event and stop_event.is_set():
            break

        # Evaluasi
        z_list       = [hitung_objektif(k, flow, dist) for k in populasi]
        fitness_list = [hitung_fitness(z) for z in z_list]

        min_idx = z_list.index(min(z_list))
        if z_list[min_idx] < best_z:
            best_z        = z_list[min_idx]
            best_kromosom = populasi[min_idx][:]
            best_fitness  = fitness_list[min_idx]

        riwayat_best.append(best_z)
        avg_z = sum(z_list) / popsize
        riwayat_avg.append(avg_z)

        if progress_callback:
            progress_callback(gen, max_gen, best_z, avg_z)

        # Elitisme
        pasangan = sorted(zip(z_list, populasi), key=lambda x: x[0])
        elite    = [copy.deepcopy(p) for _, p in pasangan[:elite_count]]

        # Crossover + Mutasi
        offspring = []
        pop_sorted = [p for _, p in pasangan]

        while len(offspring) < popsize - elite_count:
            r = random.random()
            if r < pc:
                idx1 = random.randint(0, popsize - 1)
                idx2 = random.randint(0, popsize - 1)
                while idx2 == idx1:
                    idx2 = random.randint(0, popsize - 1)
                child = order_crossover(pop_sorted[idx1], pop_sorted[idx2])
            else:
                child = pop_sorted[random.randint(0, popsize - 1)][:]

            if random.random() < pm:
                child = reciprocal_exchange_mutation(child)

            offspring.append(child)

        populasi = elite + offspring

    elapsed = time.time() - start_time
    return best_kromosom, best_z, best_fitness, riwayat_best, riwayat_avg, elapsed


def hitung_kontribusi(best_kromosom, flow, dist):
    """Hitung kontribusi biaya tiap departemen."""
    n = len(best_kromosom)
    perm = [k - 1 for k in best_kromosom]
    kontribusi = []
    for i in range(n):
        c = sum(flow[i][j] * dist[perm[i]][perm[j]] for j in range(n))
        kontribusi.append(c)
    return kontribusi